### ISSUE TITLE
Test error conditions

### ISSUE THREAD

**Issue by ollelauribostrom** [ollelauribostrom/cl-dotenv#10]
The test suite currently tests that malformed-entry/duplicated-entry conditions are raised when trying to read any of the invalid .env files in the test folder. However, the implementation of these conditions are not yet covered by any unit tests. 

Coverage report from the latest build: https://coveralls.io/jobs/40369828/source_files/1964393522

@PuercoPop Do you know how to go about testing these conditions? Is it possible/needed?

**Comment by PuercoPop** [comment]
@ollelauribostrom I'm unsure how the coverage is registered. We are testing the cases when those conditions are being signaled. Should't that count as exercising the condition?

https://github.com/ollelauribostrom/cl-dotenv/blob/986f2e41492ac0187eaedec33b4aaede72a651cf/tests/cl-dotenv.lisp#L10-L18

**Comment by ollelauribostrom** [comment]
@PuercoPop Im guessing that [(is-error)](https://github.com/fukamachi/prove#is-error-form-condition-optional-desc) only checks that a condition of a certain type is raised. I added two more test cases that checks the format of these conditions #11.

**Comment by PuercoPop** [comment]
Ah It makes sense, we weren't exercising the condition formatters!

**Comment by ollelauribostrom** [comment]
Closed by #11
