### ISSUE TITLE
Update installation steps in README.md

### ISSUE THREAD

**Issue by ollelauribostrom** [ollelauribostrom/cl-dotenv#13]
This project is now [available through Quicklisp](https://github.com/quicklisp/quicklisp-projects/commit/fa67d034163331efd333e89b05a69f1c97d4832a). The installation steps in the README needs to be updated accordingly. 

- Add something like `The package is available through [Quicklisp](http://www.quicklisp.org/beta/)`
- Remove the manual installation steps

**Comment by itsJarrett** [comment]
I will work on this.

**Comment by cdeepanshu** [comment]
I also want to work on this issue.

**Comment by ollelauribostrom** [comment]
@cdeepanshu Sorry but this has now been closed as of #15. You can work on #16 if you want 🙂

**Comment by cdeepanshu** [comment]
Yes I definitely want to work
