### ISSUE TITLE
Add support for more Lisp installations

### ISSUE THREAD

**Issue by ollelauribostrom** [ollelauribostrom/cl-dotenv#5]
This library is currently tested (in Travis CI) with SBCL, Allegro, ECL and CLISP. It would be awesome to add support for other Lisp installations as well.

Todo:
- Modify **get-env** and **set-env** in `src/cl-dotenv.lisp` to handle additional Lisp installations
- Add these Lisp installations as build targets in .travis.yml

**Comment by PuercoPop** [comment]
`uiop` wraps the get-env and set-env functionality under `uiop:getenv`. It defines a setf expander for get-env so instead of set-env we can set an environment variable like:

```
(if (and name value)
        (setf (uiop:getenv name)
              value)
        (error "Invalid ..."))
````

**Comment by ollelauribostrom** [comment]
Thanks for the tip @PuercoPop, still new to Common Lisp. #6 implements this and does also declare the dependency to uiop in cl-dotenv.asd. What are your thoughts?

**Comment by PuercoPop** [comment]
LGTM. Although `setf`ing is the more common way to assign values in Lisp.

**Comment by ollelauribostrom** [comment]
Awesome work in the [fork](https://github.com/LispLima/cl-dotenv). Seems to be more in line with the parsing rules described [here](https://github.com/motdotla/dotenv#rules). If you feel like it, open a PR and lets discuss it further 😃@PuercoPop

**Comment by PuercoPop** [comment]
@ollelauribostrom Yeah, I based myself off of those rules. Before opening a PR I wanted to finish decoupling the reading from the loading/setting to be able to provide restarts (just finished  `\( ﾟヮﾟ)/)`. Hopefully tomorrow I'll be finish writing a proper explanation of the suggestions I have in mind and open a PR so we can discuss further and see which ones you like. Btw this is how the restarts currently look

### When an entry is malformed

![image](https://user-images.githubusercontent.com/387111/45200896-7f646a00-b238-11e8-98ad-9d6643a41bdd.png)

### When an entry is duplicated
(I have to improve the wording of this condition)

![image](https://user-images.githubusercontent.com/387111/45200911-91460d00-b238-11e8-9a08-89a597e465ad.png)

**Comment by ollelauribostrom** [comment]
#7 Closes this
